name: House price estimator CI pipeline 

on:
  push:
    branches:
        - main
  pull_request:
    branches:
        - main

jobs:

    build-and-test:
        runs-on: ubuntu-latest

        steps:
            - name : Checkout code 
              uses: actions/checkout@v3

            - name : Set up Python 
              uses: actions/setup-python@v4
              with:
                  python-version: 3.9
            
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip 
                pip install -r requirements.txt


            # - name: Train the model (Online Training)
            #   run: python model.py


            - name: Run Tests
              run: pytest   

    # deploy:
    #     runs-on: ubuntu-latest

    #     steps:
    #       - name : Checkout code 
    #         uses : actions/checkout@v3

    #       - name : Authenticate to GCP 
    #         uses : actions/checkout@v3

    #       - name : Configure GCP project
    #         uses : actions/checkout@v3
          
    #       - name : Build and Push Docker Image  
    #         uses : actions/checkout@v3
          